### ISSUE TITLE
Returns

### ISSUE THREAD

**Issue by nrecoder** [CardioPy/CardioPy#20]
![Screen Shot 2020-06-18 at 11 14 12](https://user-images.githubusercontent.com/60148647/85039184-774b9500-b155-11ea-91c0-30d5336c83d6.png)
![Screen Shot 2020-06-18 at 11 18 06](https://user-images.githubusercontent.com/60148647/85039187-77e42b80-b155-11ea-8081-df94709e87ed.png)

I have seen in the code you use the returns section to mark if certain attributes have been added or changed. Online I have only seen this section used if something is specifically returned using the return command (not sure command is the right word) . I haven't been able to find something that specifically says not to do it in the cases you have used but I also haven't seen anything saying to do it. Is there a specific reason you are doing this? Given the examples I have seen I would be inclined not to use the return section unless we specifically returned something.

**Comment by jag2037** [comment]
This is a good point. I agree -- since no variable is being returned it probably shouldn't be under the Returns section. 

I was noting the attribution additions/modification in the docstrings to keep track of the main outcome of a method, since an attribute change isn't always readily apparent. We could change this to be done in a separate section (with an appropriate title) or included in the notes. Thoughts?

**Comment by jag2037** [comment]
Attribute additions/modifications are now in the "modifications" heading of method docstrings
